#1. Calculando a média de uma lista com tipos de dados diferentes

Você tem uma lista de número: [6,7,4,7,8,4,2,5,7,&#39;hum&#39;, &#39;dois&#39;]

A ideia do exercício éVtirar a média de todos os valores contidos na lista, porém para fazer o cálculo precisa remover as strings.

In [ ]:
listaNumeros = [6,7,4,7,8,4,2,5,7,'hum','dois']

#Calculando a quantidade de elementos
qtdeElementos = len(listaNumeros)

listaNumeros.remove('hum')
listaNumeros.remove('dois')

numerosValidos = sum(listaNumeros)
media = numerosValidos/qtdeElementos

print(media)

4.545454545454546


#2. Crie um método que receba duas matrizes, some o total de cada matriz e depois multiplique o resultado delas e retorne o valor

In [52]:
def obterLista1(matriz1):
  matriz1=[
           [0,0,0],
           [0,0,0],
           [0,0,0]
]
for linhasMatriz1 in range(0,3):
  for colunasMatriz1 in range(0,3):
    matriz1[linhasMatriz1][colunasMatriz1] = int(input(f'Digite um valor para [{linhasMatriz1},{colunasMatriz1}]: '))
print(matriz1)

print()

def obterLista1(matriz2):
  matriz2 = [
             [0,0,0],
             [0,0,0],
             [0,0,0]
]
for linhasMatriz2 in range(0,3):
  for colunasMatriz2 in range(0,3):
    matriz2[linhasMatriz2][colunasMatriz2] = int(input(f'Digite um valor para [{linhasMatriz2},{colunasMatriz2}]: '))
print(matriz2)

Digite um valor para [0,0]: 1
Digite um valor para [0,1]: 2
Digite um valor para [0,2]: 3
Digite um valor para [1,0]: 4
Digite um valor para [1,1]: 5
Digite um valor para [1,2]: 6
Digite um valor para [2,0]: 7
Digite um valor para [2,1]: 8
Digite um valor para [2,2]: 9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Digite um valor para [0,0]: 1
Digite um valor para [0,1]: 2
Digite um valor para [0,2]: 3
Digite um valor para [1,0]: 4
Digite um valor para [1,1]: 5
Digite um valor para [1,2]: 6
Digite um valor para [2,0]: 7
Digite um valor para [2,1]: 8
Digite um valor para [2,2]: 9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [53]:
#Somando a primneira matriz
somaContador1 = 0
for leMatriz1 in matriz1:
  for somaMatriz1 in leMatriz1:
    somaContador1 = somaContador1 + somaMatriz1

#Somando a segunda matriz
somaContador2 = 0
for leMatriz2 in matriz2:
  for somaMatriz2 in leMatriz2:
    somaContador2 = somaContador2 + somaMatriz2

#Multiplicando o resultado da soma de matrizes
multiplicacao = somaContador1*somaContador2
print(multiplicacao)

2025


#3. Criar uma matriz nxm (n = 5, m =7)


In [42]:
import numpy as np

In [43]:
matrizNxM = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1],[71,62,53,44,35,26,17],[77,66,55,44,33,22,11],[71,61,52,42,32,22,12]])
matrizNxM.shape

(5, 7)

#3. Criar uma matriz nxm (n = 5, m =7)
a. faça a matriz transposta desta matriz

In [44]:
matrizNxM = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1],[71,62,53,44,35,26,17],[77,66,55,44,33,22,11],[71,61,52,42,32,22,12]])[np.newaxis]
print(matrizNxM.T)

[[[ 1]
  [ 7]
  [71]
  [77]
  [71]]

 [[ 2]
  [ 6]
  [62]
  [66]
  [61]]

 [[ 3]
  [ 5]
  [53]
  [55]
  [52]]

 [[ 4]
  [ 4]
  [44]
  [44]
  [42]]

 [[ 5]
  [ 3]
  [35]
  [33]
  [32]]

 [[ 6]
  [ 2]
  [26]
  [22]
  [22]]

 [[ 7]
  [ 1]
  [17]
  [11]
  [12]]]


#3. Criar uma matriz nxm (n = 5, m =7)
b. somar toda matrix


In [45]:
matrizNxM.sum()

964

#3. Criar uma matriz nxm (n = 5, m =7)
c. somar todas as colunas

In [59]:
somaColunas = matrizNxM.sum(axis=2)
print(somaColunas)

[[ 28  28 308 308 292]]


#3. Criar uma matriz nxm (n = 5, m =7)
d. somar todas as linhas

In [60]:
somaLinhas = matrizNxM.sum(axis=1)
print(somaLinhas)

[[227 197 168 138 108  78  48]]


#3. Criar uma matriz nxm (n = 5, m =7)
e. retorne o *maior* valor

In [67]:
maiorValor = np.max(matrizNxM)
print(maiorValor)

77


#3. Criar uma matriz nxm (n = 5, m =7)
e. retorne o *menor* valor

In [68]:
menorValor = np.min(matrizNxM)
print(menorValor)

1


#4. Crie uma matriz nxn (n=5). Agora some essa matriz com a matriz do exercício 3

In [81]:
matriz5x5 = np.array([[1,2,3,4,5,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
somamatrizNxM_matriz5x5 = np.sum([matriz5x5,matrizNxM])
print(somamatrizNxM_matriz5x5)

[[[ 2  4  6  8 10  6  7]
  [ 7  6  5  4  3  2  1]
  [71 62 53 44 35 26 17]
  [77 66 55 44 33 22 11]
  [71 61 52 42 32 22 12]]]


/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


#5. crie um array de números que vai de 0 a 1000

In [92]:
matriz0x1000 = np.array([n for n in range(0,1001)])
print(matriz0x1000)

[   0    1    2 ...  998  999 1000]


#6. crie uma matriz só de zeros.

In [94]:
matriz0 = np.zeros(1001)
print(matriz0)

[0. 0. 0. ... 0. 0. 0.]
